fix the fake inprocess database, do various cleanups (#167)
the main thing needed was to set MaxOpenConns to 1 for the fake
DB, because it doesn't support parallel queries:
https://github.com/dolthub/go-mysql-server/issues/1306#issuecomment-2919835997

the only thing still not working in the fake DB is striking/unstriking
of report entries, because of this issue I logged:
https://github.com/dolthub/dolt/issues/9268
but a fix is incoming:
https://github.com/dolthub/go-mysql-server/pull/3000

diff --git a/bin/test_docker b/bin/test_docker
--- a/bin/test_docker
+++ b/bin/test_docker
@@ -11,17 +11,24 @@ set -o errexit -o nounset -o pipefail
 cd "$(git rev-parse --show-toplevel)"
 
 exit_code=0
-# `docker compose up` will only rebuild from the local Dockerfile if no image
-# exists for the given name, e.g. ranger-ims-go. To change that behavior, you'd
-# add a --build arg to the `docker compose up`.
-echo "Starting Docker containers. Note this may not pick up any local changes"
+image="ranger-ims-go:${IMAGE_TAG:-latest}"
+docker image inspect "${image}" > /dev/null 2>&1 || exit_code=$?
+if [ "${exit_code}" -ne "0" ]; then
+    echo "No local version of ${image} was found, so docker compose will build it"
+else
+    # If you want the image to be rebuilt, then add "--build" to the "docker compose up"
+    # below. That is not desirable behavior for CI though.
+    echo "A local version of ${image} was found, so docker compose will not rebuild it"
+fi
+
+exit_code=0
 docker compose up --wait-timeout 30 --wait || exit_code=$?
 
 echo "Stopping and deleting those Docker containers"
 docker compose rm -fsv
 
 if [ "${exit_code}" -ne "0" ]; then
-    echo "App failed health check"
+    echo '!!! App failed health check !!!'
     exit ${exit_code}
 else
     echo "App started and passed health check"
